/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EchecCaseController;
import Model.EchecModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author vmachu
 */
public class EchecView extends javax.swing.JFrame implements Observateur{
    
    //Chargement des images
    private static final ImageIcon CASE_BLANC = new ImageIcon("./src/imgs/case_blanche.png");
    private static final ImageIcon CASE_NOIR = new ImageIcon("./src/imgs/case_noire.png");
    private static final ImageIcon CB_B = new ImageIcon("./src/imgs/blanches/CB_B.png");
    private static final ImageIcon CB_N = new ImageIcon("./src/imgs/blanches/CB_N.png");
    private static final ImageIcon DB_B = new ImageIcon("./src/imgs/blanches/DB_B.png");
    private static final ImageIcon DB_N = new ImageIcon("./src/imgs/blanches/DB_N.png");
    private static final ImageIcon FB_B = new ImageIcon("./src/imgs/blanches/FB_B.png");
    private static final ImageIcon FB_N = new ImageIcon("./src/imgs/blanches/FB_N.png");
    private static final ImageIcon PB_B = new ImageIcon("./src/imgs/blanches/PB_B.png");
    private static final ImageIcon PB_N = new ImageIcon("./src/imgs/blanches/PB_N.png");
    private static final ImageIcon RB_B = new ImageIcon("./src/imgs/blanches/RB_B.png");
    private static final ImageIcon RB_N = new ImageIcon("./src/imgs/blanches/RB_N.png");
    private static final ImageIcon TB_B = new ImageIcon("./src/imgs/blanches/TB_B.png");
    private static final ImageIcon TB_N = new ImageIcon("./src/imgs/blanches/TB_N.png");
    
    //Nb de lignes et colonnes de l'échiquier
    private static final int taille = 8;
    
    //L'échiquier
    private JLabel[][] echiquier; // Le plateau
    
    private EchecModel echec; // Le jeu

    /**
     * Creates new form EchecsFrame
     */
    public EchecView(EchecModel _echec) {
        initComponents();
        
        //On rempli notre morpion
        this.echec = _echec;
        
        //Initialisation échiquier
        this.echiquier = new JLabel[taille][taille];
        
        //Pour chaque case du tableau
        for(int i=0;i<taille;i++){
            for(int j=0;j<taille;j++){
//                System.out.println("["+i+"]"+"["+j+"]");
                this.echiquier[i][j] = new JLabel(CASE_BLANC);
                //Ajout de la case à l'échiquier
                this.jPanelEchiquier.add(this.echiquier[i][j]);
                
                //Ajout d'un mouse listener
                this.echiquier[i][j].addMouseListener(
                        new EchecCaseController(i,j, this.echec));
            }
        }
        // La fenêtre va se redimensionner par rapport à tous ses composants
        this.pack();
    }
    
    void initEchiquier(){
        for(int i=0;i<taille;i++){
            for(int j=0;j<taille;j++){
                // init case
                this.echiquier[i][j].setIcon(CASE_BLANC);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEchiquier = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelEchiquierLayout = new javax.swing.GroupLayout(jPanelEchiquier);
        jPanelEchiquier.setLayout(jPanelEchiquierLayout);
        jPanelEchiquierLayout.setHorizontalGroup(
            jPanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );
        jPanelEchiquierLayout.setVerticalGroup(
            jPanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jMenu1.setText("Nouvelle partie");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quitter");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEchiquier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEchiquier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        this.echec.nouvellePartie();
        initEchiquier();
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
             public void run() {
                // On instancie notre modèle
                EchecModel echec = new EchecModel();
                
                // On instancie notre frame
                EchecView view = new EchecView(echec);
                
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelEchiquier;
    // End of variables declaration//GEN-END:variables

    @Override
    public void avertir(int i, int j) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void avertirNouvellePartie() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void avertirFinPartie(boolean avecGagnant) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
