/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.EchecCaseController;
import Model.EchecModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author vmachu
 */
public class EchecView extends javax.swing.JFrame implements Observateur {

    //Chargement des images
    private static final ImageIcon CASE_BLANC = new ImageIcon("./src/imgs/case_blanche.png");
    private static final ImageIcon CASE_NOIR = new ImageIcon("./src/imgs/case_noire.png");
    private static final ImageIcon CB_B = new ImageIcon("./src/imgs/blanches/CB_B.png");
    private static final ImageIcon CB_N = new ImageIcon("./src/imgs/blanches/CB_N.png");
    private static final ImageIcon DB_B = new ImageIcon("./src/imgs/blanches/DB_B.png");
    private static final ImageIcon DB_N = new ImageIcon("./src/imgs/blanches/DB_N.png");
    private static final ImageIcon FB_B = new ImageIcon("./src/imgs/blanches/FB_B.png");
    private static final ImageIcon FB_N = new ImageIcon("./src/imgs/blanches/FB_N.png");
    private static final ImageIcon PB_B = new ImageIcon("./src/imgs/blanches/PB_B.png");
    private static final ImageIcon PB_N = new ImageIcon("./src/imgs/blanches/PB_N.png");
    private static final ImageIcon RB_B = new ImageIcon("./src/imgs/blanches/RB_B.png");
    private static final ImageIcon RB_N = new ImageIcon("./src/imgs/blanches/RB_N.png");
    private static final ImageIcon TB_B = new ImageIcon("./src/imgs/blanches/TB_B.png");
    private static final ImageIcon TB_N = new ImageIcon("./src/imgs/blanches/TB_N.png");

    //Nb de lignes et colonnes de l'échiquier
    private static final int taille = 8;

    JButton btnQuitter = new JButton("Q");
    //L'échiquier
    JLabel[][] jlEchiquier; // Le plateau

    private EchecModel m_echec; // Le jeu

    /**
     * Creates new form EchecsFrame
     */
    public EchecView(EchecModel _echec) {
        initComponents();

        jPanelEchiquier.add(btnQuitter);
        this.m_echec = _echec;

        this.jlEchiquier = new JLabel[taille][taille];

        //Pour chaque case du tableau
        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {
                
//                System.out.println("["+i+"]"+"["+j+"]");
                jlEchiquier[i][j] = new JLabel(CASE_BLANC);
                //Ajout de la case à l'échiquier
                jPanelEchiquier.add(jlEchiquier[i][j]);

                //Ajout d'un mouse listener
                jlEchiquier[i][j].addMouseListener(
                        new EchecCaseController(i, j, m_echec));
            }
        }
        // La fenêtre va se redimensionner par rapport à tous ses composants
        this.pack();
    }

    void initiatlisationEchiquier() {
        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {
                // init case
                jlEchiquier[i][j].setIcon(CASE_BLANC);
            }
        }
    }

    public void majGraphique(int i, int j) {
        System.out.println("coucou");
    }

    @Override
    public void avertir(int i, int j) {
        majGraphique(i, j);
    }

    @Override
    public void avertirNouvellePartie() {
        initiatlisationEchiquier();
    }

    @Override
    public void avertirFinPartie() {
        JOptionPane.showMessageDialog(null, "Echec et Mat !",
                "Fin de la partie", JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelEchiquier = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        nouvellePartie = new javax.swing.JMenu();
        quitter = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelEchiquierLayout = new javax.swing.GroupLayout(jPanelEchiquier);
        jPanelEchiquier.setLayout(jPanelEchiquierLayout);
        jPanelEchiquierLayout.setHorizontalGroup(
            jPanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelEchiquierLayout.setVerticalGroup(
            jPanelEchiquierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        nouvellePartie.setText("Nouvelle partie");
        nouvellePartie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nouvellePartieMouseClicked(evt);
            }
        });
        jMenuBar1.add(nouvellePartie);

        quitter.setText("Quitter");
        quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterMouseClicked(evt);
            }
        });
        jMenuBar1.add(quitter);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanelEchiquier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanelEchiquier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nouvellePartieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nouvellePartieMouseClicked
        m_echec.nouvellePartie();
    }//GEN-LAST:event_nouvellePartieMouseClicked

    private void quitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterMouseClicked
        this.dispose();
    }//GEN-LAST:event_quitterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EchecView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                EchecModel model = new EchecModel();
                EchecView view = new EchecView(model);
                
                //ajout de la vue au modele comme observateur
                model.ajouterObservateur(view);

                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelEchiquier;
    private javax.swing.JMenu nouvellePartie;
    private javax.swing.JMenu quitter;
    // End of variables declaration//GEN-END:variables

}
